ncsoft/ncresearch

- _sass/base/_global.scss
> delete overflow-x hidden

- notebooks/varco_model_13_FM.ipynb
- notebooks/varco_model_13_IST.ipynb
- notebooks/varco_model_1_3_FM.ipynb
- notebooks/varco_model_1_3_IST.ipynb
- notebooks/varco_model_6_4_FM.ipynb
- notebooks/varco_model_6_4_IST.ipynb
> 언어모델팀 업데이트

- _sass/base/_global.scss
- _sass/includes/_navbar.scss
> 모바일 대응 추가 

- _sass/base/_global.scss
- pages/01_about.md
> About 조직 테이블 코딩 변경

- notebooks/VARCO LLM KO-EN-13B-IST.ipynb
- notebooks/VARCO LLM KO-EN-6_4B-IST.ipynb
> VARCO LLM 모델 2가지 추가 (언어모델팀)

- notebooks/VARCO LLM KO-EN-13B-IST.ipynb
- notebooks/VARCO LLM KO-EN-6_4B-IST.ipynb
> VARCO LLM 모델 추가 내용 수정 (언어모델팀)

- pages/varco_llm_detail.md
> VARCO LLM Details 페이지 Data Details 제거

- _posts/2023-09-21-reduce-animation-production-time-through-motion-capture-data-post-processing-automation-technology.md
> 신규 컨텐츠 업로드 : open

- _sass/external/font-awesome/_variables.scss
> css 문법 오류 수정

- _posts/2023-09-26-airport-weather-information.md
> posting-0927 : 수정 내용 적용5

- _posts/2023-09-26-cross-entropy.md
> posting-0927 : 수정 내용 적용6

- _posts/2023-10-11-what-can-language-models-do-in-finance.md
> table of contents 추가

- _posts/2023-10-12-what-can-language-models-do-in-finance.md
> post index 수정

- _posts/2023-08-10-put-a-name-tag-on-your-chest.md
- _posts/2023-08-15-machines-can-recognize-emotions.md
- _posts/2023-09-21-reduce-animation-production-time-through-motion-capture-data-post-processing-automation-technology.md
> 오래된 컨텐츠 new 제거

- _posts/2023-10-27-shout-out-summaries-at-the-center-of-search_2.md
> NLP Center 10월 - 컨텐츠 수정

- _posts/2023-10-27-shout-out-summaries-at-the-center-of-search_2.md
> NLP Center 10월 - 컨텐츠 수식 수정

- _posts/2023-10-27-shout-out-summaries-at-the-center-of-search_2.md
> NLP Center 10월 - 잘못된 이미지 제거

- _posts/2023-10-31-artificial-intelligence-thinking-a-path-to-complex-reasoning.md
- _posts/2023-10-31-shout-out-summaries-at-the-center-of-search_2.md
> NLP Center 10월 - 글 공개

- pages/02_varco_llm.md
> LLM 소개 영상 교체

- _posts/2023-11-24-dig-up-treasure-from-the-scattered-subtitles.md
> 정렬 부분 수정, 코드 부분 수정

- _posts/2023-11-28-dig-up-treasure-from-the-scattered-subtitles.md
> 수정 내용 적용 및 글 공개

- _data/authors.yml
> December upload

- _posts/2023-12-12-large-language-model-2.md
> fix image size

- _posts/2023-12-12-large-language-model-2.md
> NLP December post confirm

- _posts/2024-01-17-texture-copilot.md
> apply modifications

- _posts/2024-01-25-varco-mt.md
> fix table align
